# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_config": "config.ipynb",
         "Paths": "config.ipynb",
         "p": "paths.ipynb",
         "Config": "config.ipynb",
         "config": "config.ipynb",
         "simplecache": "caching.ipynb"}

modules = ["config.py",
           "paths.py",
           "caching.py"]

doc_url = "https://antonbabkin.github.io/reseng/"

git_url = "https://github.com/antonbabkin/reseng/tree/master/"

def custom_doc_links(name): return None
