# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/nbs/caching.ipynb (unless otherwise specified).

__all__ = ['simplecache']

# Cell
#export
import pathlib
import pickle

from .config import Paths

# Cell
def simplecache(path):
    def wrapper(func):
        def wrapped(*args, **kwargs):
            p = pathlib.Path(path)
            if p.exists():
                print(f'Reading {func.__name__}() cached result from "{path}".')
                return pickle.load(p.open('rb'))
            else:
                res = func(*args, **kwargs)
                print(f'Writing {func.__name__}() result to cache at "{path}".')
                pickle.dump(res, p.open('wb'), protocol=5)
                return res
        return wrapped
    return wrapper